import React from 'react'

export const About = () => (
	<div>
		<h2>About</h2>
		<p>
		Iam nunc quaeramus diligentius quantum dat deus quod paulo ante distulimus, utrum et singula quaeque in trinitate persona possit et per se ipsam non cum ceteris duabus dici deus aut magnus aut sapiens aut uerus aut omnipotens aut iustus et si quid aliud de deo dici potest, non relatiue sed ad se ipsum, an uero non dicantur ista nisi cum trinitas intellegitur. Hoc enim quaestionem facit quia scriptum est: Christum dei uirtutem et dei sapientiam, utrum ita sit pater sapientiae atque uirtutis suae ut hac sapientia sapiens sit quam genuit et hac uirtute potens quam genuit, et quia semper potens et sapiens, semper genuit uirtutem et sapientiam. Dixeramus enim si ita est cur non et magnitudinis suae pater sit qua magnus est et bonitatis qua bonus et iustitiae qua iustus et alia si qua sunt. Aut si haec omnia pluribus uocabulis in eadem sapientia et uirtute intelleguntur ut ea sit magnitudo quae uirtus, ea bonitas quae sapientia, et ea rursus sapientia quae uirtus sicut iam tractauimus, meminerimus cum aliquid horum nomino sic accipiendum esse ac si omnia commemorem.Iam nunc quaeramus diligentius quantum dat deus quod paulo ante distulimus, utrum et singula quaeque in trinitate persona possit et per se ipsam non cum ceteris duabus dici deus aut magnus aut sapiens aut uerus aut omnipotens aut iustus et si quid aliud de deo dici potest, non relatiue sed ad se ipsum, an uero non dicantur ista nisi cum trinitas intellegitur. Hoc enim quaestionem facit quia scriptum est: Christum dei uirtutem et dei sapientiam, utrum ita sit pater sapientiae atque uirtutis suae ut hac sapientia sapiens sit quam genuit et hac uirtute potens quam genuit, et quia semper potens et sapiens, semper genuit uirtutem et sapientiam. Dixeramus enim si ita est cur non et magnitudinis suae pater sit qua magnus est et bonitatis qua bonus et iustitiae qua iustus et alia si qua sunt. Aut si haec omnia pluribus uocabulis in eadem sapientia et uirtute intelleguntur ut ea sit magnitudo quae uirtus, ea bonitas quae sapientia, et ea rursus sapientia quae uirtus sicut iam tractauimus, meminerimus cum aliquid horum nomino sic accipiendum esse ac si omnia commemorem.
		</p>
	</div>
	)